/** EFIDE Studio 화면설계서(Figma) 기준 레이아웃·타이포 스펙 */
export const figma = {
  layout: {
    topBar: 'h-[52px] px-6',
    activityBar: 'w-12',
    fileTree: 'w-[240px]',
    rightPanel: 'w-[300px] xl:w-[320px]',
    adminSidebar: 'w-[224px]',
    contentMax: 'max-w-[1200px]',
    authSplit: 'lg:w-1/2',
    authForm: 'max-w-[440px]',
    modalMd: 'max-w-[520px]',
    modalXl: 'max-w-[800px]',
  },
  spacing: {
    page: 'px-6 py-8',
    card: 'p-6',
    cardCompact: 'p-4',
    stack: 'space-y-6',
    inline: 'gap-3',
  },
  typography: {
    display: 'text-[32px] font-bold leading-[40px] tracking-[-0.02em]',
    h1: 'text-[28px] font-bold leading-[36px] tracking-[-0.01em]',
    h2: 'text-lg font-semibold leading-7',
    h3: 'text-base font-semibold leading-6',
    body: 'text-sm leading-5',
    caption: 'text-xs leading-4',
    label: 'text-sm font-medium leading-5',
  },
  sizes: {
    inputHeight: 'h-10',
    buttonHeight: 'h-10',
    tableRow: 'h-12',
    projectCardMin: 'min-h-[140px]',
    avatarLg: 'h-20 w-20',
    avatarSm: 'h-8 w-8',
    iconBtn: 'h-9 w-9',
  },
  colors: {
    minimal: {
      primary: '#0969DA',
      border: '#D0D7DE',
      bgMuted: '#F6F8FA',
      text: '#1F2328',
      textMuted: '#656D76',
    },
    saas: {
      primary: '#4F46E5',
      border: '#E2E8F0',
      bgMuted: '#F8FAFC',
      text: '#0F172A',
      textMuted: '#64748B',
    },
    dark: {
      primary: '#0E639C',
      border: '#3E3E42',
      bgEditor: '#1E1E1E',
      bgPanel: '#252526',
      bgActivity: '#333333',
      text: '#CCCCCC',
      textMuted: '#9D9D9D',
      accentOrange: '#E39451',
    },
  },
} as const;
